name: Helper

on:
  pull_request:
    types:
      - closed

jobs:
  instructions:
    name: instructions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        with:
          script: |
            const creator = context.payload.sender.login
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
              creator,
              state: 'all'
            })
            const issues = await github.paginate(opts)
            const { instructions } = require(`${process.env.GITHUB_WORKSPACE}/scripts/reply.js`);
            await instructions(context, github);


            
